name: publish-website

on:
  push:
    branches:
      - master

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    steps:
        - name: Contribute List
          uses: akhilmhdh/contributors-readme-action@v2.3.6
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish-packages:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          cache: yarn
      - run: yarn
      - run: yarn run build
      # 👆 Build steps
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # 👇 Specify build output path
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2